### PR TITLE
Update Readme with more details regarding Python 2

### PR DESCRIPTION
**Pull request by shadinaif**
There are many troubles to face the developer when it comes to FontForge with Python 3. Therefore; this PR is to update the README.md file to address some safe practices to avoid these troubles

### CODE REVIEW

**Comment by khaledhosny** [comment]
I use Python 3 and I don’t recommend using 2.7 which will reach EOL rather soon.

**Comment by khaledhosny** [comment]
Debian/Ubuntu provide `python-fontforge` package and I think other packages do as well, so if you are on Linux then you don’t need to build from source at all. I don’t think FontForge build instructions belong here.

**Comment by shadinaif** [comment]
Thank you for reply @khaledhosny 
I went into a loop for many hours trying to use Python 3 with and without the source but didn't have any luck with that. And I found many other users complaining about Python 3 issues. Are you using fontforge on Ubuntu yourself?
For me, I always get the following error with `make ttf` when I try to use Python 3.5:
```
File "tools/build.py", line 18, in <module>
    import fontforge
ImportError: No module named fontforge
```

**Comment by khaledhosny** [comment]
I use Arch Linux which has Python 3 as default (`/usr/bin/python` is Python 3 not 2) and FontForge is working fine. If one’s distribution does not provide FontForge module for Python 3, then one has to use Python 2 for sure, but I don’t think we need to explicitly document this here.

**Comment by shadinaif** [comment]
Thank you @khaledhosny 
I can change the PR to show a separate section for Ubuntu 16.04 users for how to install it using Python 2.7
Please let me know if that would be acceptable for you. Otherwise, we will close this PR

**Comment by khaledhosny** [comment]
Steps for Ubuntu would be good.

**Comment by shadinaif** [comment]
Done dear @khaledhosny

**Comment by khaledhosny** [comment]
Thanks!

**Comment by shadinaif** [comment]
Thank you @khaledhosny :tada:

**Pull request merged**
