### PR TITLE
Format `README-Arabic.md` file

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by khaledhosny** [comment]
Thank you, but the space (NBSP) is intentional, although I know it is not a common style.

**Comment by atefBB** [comment]
I think it's a common style, see in the Quran you will not find a `waw` alone (especially if it's a `waw 'atf` واو عطف)!

**Comment by khaledhosny** [comment]
That is why I use no break space, the waw will never be alone at the end of the line. In the middle of the line, Arabic did not usually make a difference between spaces inside the word or between words, it is a modern convention and I like to make clear whether _waw_ is part of the word or not.

**Comment by atefBB** [comment]
<div dir="rtl">بما أن الواو لها اتصال بما بعدها وهي أداة -وليست حرفا بالمعنى اﻷباجيدي إن صح التعبير- لذلك التصقت بما هي متعلقة به من المعطوف والفعل أو غيره.</div>

**Pull request closed without merging**
